# 量化交易系统配置文件

# 数据库配置
database:
  type: "sqlite"
  path: "databases/quant_system.db"
  echo: false
  pool_size: 5
  max_overflow: 10

# 数据源配置
data_sources:
  default: "akshare"
  akshare:
    enabled: true
    timeout: 30
  yahoo:
    enabled: false
    timeout: 30

# 事件引擎配置
event_engine:
  max_queue_size: 10000
  process_timeout: 1.0
  enable_history: true
  max_history_size: 10000

# 交易配置
trading:
  initial_cash: 1000000.0
  commission_rate: 0.0003
  slippage_rate: 0.0001
  max_position_ratio: 0.1
  max_total_risk: 0.2

# 风险管理配置
risk_management:
  stop_loss_ratio: 0.05
  max_drawdown: 0.15
  var_confidence: 0.05
  position_limit: 20

# 策略配置
strategies:
  default_config:
    lookback_period: 20
    signal_threshold: 0.5
    rebalance_frequency: "daily"

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/system.log"
  max_size: "10MB"
  backup_count: 5

# 系统配置
system:
  timezone: "Asia/Shanghai"
  max_workers: 4
  debug: false
